name = input("Enter your name: ")
print("Hello "+name+"!")
r = float(input("Enter circle radius: "))
area = (r*3.14)
print("area of circle is:", area)
l = float(input("Enter length: "))
w = float(input("Enter width: "))
perimeter = 2*(l+w)
rectangle_area = (l*w)
print("rectangle perimeter is:", perimeter)
print("rectangle area is:", rectangle_area)
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
num3 = int(input("Enter third number: "))
sums = num1+num2+num3
product = num1*num2*num3
average = sums/3
print("sum of 3 number is:", sums)
print("product of 3 number is:", product)
print("average of 3 number is:", average)
talents = float(input("Enter talents: "))
pounds = float(input("Enter pounds: "))
lots= float(input("Enter lots: "))
grams = (((((talents*20)+pounds)*32)+lots)*13.3)
kilograms = int(grams/1000)
gram = round(grams - kilograms*1000,2)
print("The weight in modern units:", kilograms, "kilograms and", gram, "grams")
